# Generated by Django 4.0.3 on 2022-05-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('poster_url', models.URLField()),
                ('release_year', models.PositiveSmallIntegerField()),
                ('duration', models.DurationField()),
                ('rating', models.FloatField()),
                ('plot', models.TextField()),
                ('trending', models.BooleanField()),
                ('directors', models.ManyToManyField(to='webpage.director')),
                ('genres', models.ManyToManyField(to='webpage.genre')),
            ],
        ),
    ]
