# Generated by Django 4.0.3 on 2022-05-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
    ]
